language: python
python:
- 3.5

cache:
  pip: true
  directories:
  - env

env:
  global:
  - FLASK_COVERAGE=1

install:
- pip install -r ./requirements/dev.txt
- pip install coveralls

script:
- coverage run --source=. manage.py test

after_success:
- coveralls

notifications:
  email:
    on_success: never
    on_failure: change