language: python
python:
- 3.5

cache:
  pip: true
  directories:
  - env

install:
- pip install -r ./requirements/dev.txt
- pip install coveralls

script:
- python manage.py test

after_success:
- coveralls

notifications:
  email:
    on_success: never
    on_failure: change