language: python
python:
- 3.5

cache:
  pip: true
  directories:
  - env

install:
- pip install coveralls scrutinizer-ocular

before_script:
- pip install requirements/dev.txt

script:
- python manage test

after_success:
- coveralls
- ocular

notifications:
  email:
    on_success: never
    on_failure: change